version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: midc_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/midc_db
    depends_on:
      - db

  frontend-angular:
    build: ./frontend-angular
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  frontend-react:
    build: ./frontend-react
    container_name: react_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata: