FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
# Se o build do Angular gerar dentro da pasta browser (comum no Angular 17+), 
# ajuste o caminho abaixo para: /app/dist/frontend-angular/browser
COPY --from=builder /app/dist/frontend-angular /usr/share/nginx/html
EXPOSE 80